version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/flask-app-mysql
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/deploy_database.sh
      timeout: 60
      runas: root
    - location: scripts/install_application.sh
      timeout: 120
      runas: root
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root
    - location: scripts/start_server.sh
      timeout: 60
      runas: root